<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <AssemblyName>ConPty</AssemblyName>
    <RootNamespace>ConPty</RootNamespace>
  </PropertyGroup>

</Project>
